development:
  adapter: postgresql
  database: junethack-dev

production:
  adapter: postgresql
  database: junethack-prod

test:
  adapter: postgresql
  database: junethack-test
  user: junethack
  password: junethack
