production:
  adapter: postgresql
  database: <%= ENV['JUNETHACK_POSTGRES_DATABASE'] || 'junethack' %>
  host: <%= ENV['JUNETHACK_POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['JUNETHACK_POSTGRES_USER'] || 'junethack' %>
  password: <%= ENV['JUNETHACK_POSTGRES_PASSWORD'] || 'test' %>

development:
  adapter: postgresql
  database: <%= ENV['JUNETHACK_POSTGRES_DATABASE'] || 'junethack-dev' %>
  host: <%= ENV['JUNETHACK_POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['JUNETHACK_POSTGRES_USER'] || 'junethack' %>
  password: <%= ENV['JUNETHACK_POSTGRES_PASSWORD'] || 'test' %>

test:
  adapter: postgresql
  database: <%= ENV['JUNETHACK_POSTGRES_DATABASE'] || 'junethack-test' %>
  host: <%= ENV['JUNETHACK_POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['JUNETHACK_POSTGRES_USER'] || 'junethack' %>
  password: <%= ENV['JUNETHACK_POSTGRES_PASSWORD'] || 'test' %>
