# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.

# Coverage
require 'simplecov'
SimpleCov.start do
  add_filter "/spec/" # don't generate coverage for the unitttests

  add_group "Models", "models"
end

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end

require 'rubygems'
require 'bundler/setup'

require './lib/junethack'

ENV['RACK_ENV'] = 'test'
require 'database'

def clean_database
  ClanScoreEntry.destroy!
  Individualtrophy.destroy!
  Scoreentry.destroy!
  NormalizedDeath.destroy!
  CompetitionScoreEntry.destroy!
  Event.destroy!
  Game.destroy!
  Clan.destroy!
  User.destroy!
  Server.destroy!
end
