# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.

# Coverage
require 'simplecov'
SimpleCov.start do
  add_filter "/spec/" # don't generate coverage for the unitttests

  add_group "Models", "models"
end

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end

require 'rubygems'
require 'bundler/setup'

require './lib/junethack'

ENV['RACK_ENV'] = 'test'
require 'database'

# Load schema into in-memory test database
require 'load_structure_sql'
load_structure_sql(ActiveRecord::Base.connection)

def clean_database
  ClanScoreEntry.destroy_all
  ClanScoreHistory.destroy_all
  Individualtrophy.destroy_all
  Scoreentry.destroy_all
  NormalizedDeath.destroy_all
  CompetitionScoreEntry.destroy_all
  Event.destroy_all
  Game.destroy_all
  Clan.destroy_all
  User.destroy_all
  Server.destroy_all
  Trophy.destroy_all
end
